# Generated by Django 4.2.3 on 2023-07-15 15:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to='photos/sellers')),
                ('specialiste', models.CharField(max_length=400)),
                ('available', models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=10)),
                ('address', models.CharField(max_length=400)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('birthday', models.DateField()),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('description', models.TextField()),
                ('skills', models.CharField(blank=True, max_length=400)),
                ('reviews', models.IntegerField()),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_video', models.FileField(null=True, upload_to='videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
                ('post_image', models.ImageField(null=True, upload_to='photos/posts')),
                ('post_title', models.CharField(max_length=200)),
                ('post_description', models.TextField()),
                ('materials', multiselectfield.db.fields.MultiSelectField(choices=[('PLA (Polylactic Acid)', 'PLA (Polylactic Acid)'), ('ABS (Acrylonitrile Butadiene Styrene)', 'ABS (Acrylonitrile Butadiene Styrene)'), ('PET (Polyethylene Terephthalate)', 'PET (Polyethylene Terephthalate)'), ('NYLON', 'NYLON'), ('TPU (Thermoplastic Polyurethane)', 'TPU (Thermoplastic Polyurethane)'), ('Polycarbonate', 'Polycarbonate'), ('Metal', 'Metal'), ('Wood', 'Wood'), ('Carbon Fiber', 'Carbon Fiber'), ('Glass', 'Glass')], max_length=100)),
                ('post_keywords', models.CharField(blank=True, max_length=300)),
                ('maxSize_height', models.IntegerField()),
                ('maxSize_width', models.IntegerField()),
                ('reviews', models.IntegerField()),
                ('nb_reviews', models.IntegerField(default=0)),
                ('free_delivery', models.CharField(choices=[('Available', 'Available'), ('Not available', 'Not available')], max_length=20)),
                ('return_delivery', models.CharField(choices=[('Available', 'Available'), ('Not available', 'Not available')], max_length=20)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.seller')),
            ],
        ),
    ]
