# Generated by Django 4.2.3 on 2023-07-16 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='reviews',
        ),
        migrations.AddField(
            model_name='reviews',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.post'),
            preserve_default=False,
        ),
    ]
