# Generated by Django 4.2.3 on 2023-07-16 20:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_remove_post_reviews_reviews_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
