# Generated by Django 4.2.3 on 2023-07-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_reviews_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='lat',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='seller',
            name='lng',
            field=models.FloatField(default=1),
        ),
    ]
