# Generated by Django 4.2.3 on 2023-07-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_seller_lat_seller_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='seller',
            name='lng',
            field=models.FloatField(),
        ),
    ]
